image: golang:1.13.5

services:
  - terraform:latest

variables:
  REPO: github.com
  GROUP: sverze
  PROJECT: aws-terraform-s3-private-bucket

stages:
 - test

before_script:
  - mkdir -p $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds
  - cp -r $CI_PROJECT_DIR $GOPATH/src/$REPO/$GROUP/$PROJECT
  - ln -s $GOPATH/src/$REPO/$GROUP $GOPATH/src/_/builds/$GROUP
  - go get -v -d ./...

integration_tests:
  stage: test
  script:
    - go mod init "$REPO/$GROUP/$PROJECT"
    - go test -v ./... -coverprofile .testCoverage.txt
