# Replace "projectname" and "username"
image:
  name: hashicorp/terraform:light

before_script:
  - terraform version
  - go version
  - cd src/main/terraform/

stages:
  - validate

validate:
  stage: validate
  script:
    - terraform validate
